[package]
name = "tauri-app"
version = "0.0.1"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.3", features = [] }

[dependencies]
tauri = { version = "1.3", features = [ "window-create",
	"clipboard-all",
	"global-shortcut-all",
	"path-all",
	"shell-open",
	"system-tray",
	"window-hide",
	"window-set-size",
	"window-show",
	"window-start-dragging",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
open = "4.1.0"
ignore = "0.4.18"
metered = "0.9.0"
csv = "1.1"
thiserror = "1.0"
crossbeam-channel = "0.5"
lazy_static = "1.4.0"
tantivy = "0.20.2"
log = "0.4.19"
once_cell = "1.18.0"
chrono = "0.4.37"
env_logger = "0.11.3"


[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
